# Generated by Django 3.1.3 on 2021-12-13 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_auto_20211213_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='modify_data',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='modify_data',
            new_name='modify_date',
        ),
    ]
